server {
    listen 80;
    server_name adlinkfly.online www.adlinkfly.online 103.137.185.78;
    root /var/www/adlinkfly/webroot;
    index index.php;

    access_log /var/log/nginx/adlinkfly-access.log;
    error_log /var/log/nginx/adlinkfly-error.log;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\. {
        deny all;
    }

    client_max_body_size 10M;
}
