<?php
file_put_contents("/var/www/adlinkfly/copy_templates.php", base64_decode("PD9waHAKCmZvcmVhY2goZ2xvYigiL3Zhci93d3cvYWRsaW5rZmx5L3BsdWdpbnMvKi90ZW1wbGF0ZXMvKiIpIGFzICRkKSB7CiAgICAkbG93ZXIgPSBzdG9sbG93ZXIoJGQpOwogICAgaWYoIWlzX2RpcihkbHlwZXIoJGQpICYmIGlzX2RpcihkKSkgewogICAgICAgIGNvcHYoJGQsICRsb3dlcik7CiAgICB9Cn0KCmVjaG8gIkRvbmUiOwo="));
echo "Done";
